image: node:16.5.0
pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - client/node_modules/
  script:
    - npm install
    - npm run build
    - cp -a client/dist/. client/public/
  artifacts:
    paths:
      - client/public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
